---

# check if FILE exists
# yes:
#   pass
# no:
#   try to install packages
#   touch FILE
#   pass

- name: ensure python and required modules are installed
  raw: if test ! -f {{ prepare_file }}; then apt-get update -qq && apt-get install python python-apt -qqy && touch {{ prepare_file }}; else true; fi
  changed_when: false
